const mission={title:"Lot 2 Photography",welcome:{eyebrow:"Today’s field companion",title:"Let’s document the property together.",body:"This is here to keep us moving, help us remember the useful shots, and make the morning feel organized—not complicated.",note:"Either teammate can lead or operate at any point. We can switch naturally as we go."},objectives:[
{title:"Entrance & Approach",why:"Start with the view someone gets when arriving at the property.",capture:["A wide photo showing the entrance in context","The transition from the road into the driveway","A slow approach view toward the property"],check:"Could someone who has never visited understand how the property is entered?"},
{title:"Driveway Corridor",why:"Record the route, turns, grade changes, and places where larger vehicles may have difficulty.",capture:["A slow pass following the driveway","A higher view showing the overall route","Any tight, steep, narrow, or obstructed areas"],check:"Can we follow the driveway from the entrance to the clearing without losing orientation?"},
{title:"Whole Property",why:"Show Lot 2 as one connected place before focusing on individual areas.",capture:["One broad overview of the parcel","The clearing, driveway, wooded areas, and west side together","Recognizable landmarks that help preserve orientation"],check:"Would this help us explain the property to someone who has never been there?"},
{title:"Primary Home Area",why:"Collect views that will help us think about house placement, floor height, terrain, and the western view.",capture:["The usable home area with surrounding terrain","Opposing angles or one slow orbit","Foreground, slope, trees, and horizon together"],check:"Do the images show both the home area and what surrounds it?"},
{title:"Western View",why:"Compare how the view changes from different positions and heights.",capture:["Several distinct viewing heights","A level horizon","Foreground trees and other obstructions","More than one possible viewing position"],check:"Can we compare where the view begins to open—and what blocks it?"},
{title:"Proposed Shop Area",why:"Record the lower area being considered for the shop and vehicle access.",capture:["One overhead or plan-like view","One lower angled view","Likely truck and trailer approach paths","Nearby terrain and visible constraints"],check:"Can we understand the usable area and how a vehicle would reach it?"},
{title:"Septic & Reserve Context",why:"Keep the protected septic areas visible while thinking about buildings, access, and utilities.",capture:["The septic and reserve areas using visible landmarks","Their relationship to the home and shop areas","Anything that may need clearer field marking later"],check:"Are the important relationships clear without pretending we captured surveyed boundaries?"},
{title:"Terrain & Drainage Clues",why:"Record visible slopes, low areas, runoff paths, and anything worth asking a professional about.",capture:["Angled views that reveal grade changes","Low areas, channels, erosion, or standing water","Vegetation changes that may suggest drainage"],check:"Did we capture the places most likely to deserve closer survey or engineering attention?"},
{title:"Trees & Obstructions",why:"Preserve a baseline of the major vegetation affecting views, access, clearing, or construction.",capture:["Major tree groups in site context","Trees affecting the western view","Dense areas or likely construction obstructions","Canopy and ground-level context where practical"],check:"Can we tell which vegetation matters—and why?"},
{title:"Closing Overview",why:"Finish with one calm sequence that ties the property together.",capture:["A slow, stable overview","The entrance, home area, shop area, and western context","Clarity over cinematic movement"],check:"Would this be the first clip we would show a lender, builder, or family member?"}]};