const STORAGE_KEY = 'monticellOPS_mission2_v1';
const concerns = [
  {id:'qualification',title:'Can we qualify for financing?'},
  {id:'inProcess',title:'Can we afford the construction period?'},
  {id:'family',title:'Can the family handle the transition?'},
  {id:'temporary',title:'Could we get stuck living in the trailer?'},
  {id:'complete',title:'Can we afford the completed project?'},
  {id:'possible',title:'Is the overall plan actually possible?'}
];
const questions = [
  {id:'borrowers',section:'household position',text:'Who is expected to apply for the construction loan?',help:'List the intended borrowers and any relevant employment context.',type:'textarea',concern:'qualification',impact:'critical'},
  {id:'income',section:'household position',text:'What dependable gross income should a lender evaluate?',help:'Use current annual or monthly income. Supporting paystubs and W-2s can be added later.',type:'textarea',concern:'qualification',impact:'critical',evidence:'Recent paystubs and two years of W-2s'},
  {id:'debts',section:'household position',text:'What recurring debts and minimum monthly payments exist?',help:'Include credit cards, vehicles, student loans, personal loans, and other required payments.',type:'textarea',concern:'qualification',impact:'critical',evidence:'Current account statements or credit report'},
  {id:'cash',section:'household position',text:'How much cash is available, and how much must remain untouched?',help:'Separate project-available funds from the minimum family reserve.',type:'textarea',concern:'inProcess',impact:'critical',evidence:'Recent bank or investment statements'},
  {id:'land',section:'property and transaction',text:'What is currently owed to complete the land purchase?',help:'Include the agreed price, amount already paid, and remaining balance.',type:'textarea',concern:'possible',impact:'critical',evidence:'Purchase agreement and current payoff documentation'},
  {id:'approvals',section:'property and transaction',text:'Which property approvals and recorded documents are already complete?',help:'Examples include short plat recording, septic approval, survey, title work, and permits.',type:'textarea',concern:'possible',impact:'important',evidence:'Recorded documents, approvals, surveys, and permit records'},
  {id:'scopeMust',section:'project scope',text:'What must be included in the first funded construction phase?',help:'Identify the minimum scope required for the family to move in and the project to function.',type:'textarea',concern:'possible',impact:'critical'},
  {id:'scopeDefer',section:'project scope',text:'What could be deferred without undermining the project?',help:'Separate required scope from desirable but postponable work.',type:'textarea',concern:'possible',impact:'important'},
  {id:'housing',section:'temporary living',text:'What is the intended living arrangement during construction?',help:'Describe the trailer, utilities, location, timing, and any fallback housing option.',type:'textarea',concern:'temporary',impact:'critical'},
  {id:'familyLimits',section:'family transition',text:'What conditions would make the construction process unacceptable for the family?',help:'Consider school, privacy, storage, weather, pets, commute, and maximum tolerable duration.',type:'textarea',concern:'family',impact:'important'},
  {id:'duration',section:'construction period',text:'What construction duration should we plan around?',help:'A conservative estimate is useful even before a contractor schedule exists.',type:'text',concern:'inProcess',impact:'critical'},
  {id:'duringCosts',section:'construction period',text:'Which monthly costs will continue or begin during construction?',help:'Include rent, loan interest, utilities, insurance, storage, trailer costs, and commuting.',type:'textarea',concern:'inProcess',impact:'critical'},
  {id:'delay',section:'construction period',text:'How much delay or cost overrun should the plan survive?',help:'State a minimum reserve, number of months, or percentage contingency.',type:'textarea',concern:'inProcess',impact:'critical'},
  {id:'completedPayment',section:'completed project',text:'What completed monthly housing cost would still feel sustainable?',help:'Include mortgage, taxes, insurance, utilities, maintenance, and required financial breathing room.',type:'textarea',concern:'complete',impact:'critical'},
  {id:'rental',section:'completed project',text:'What rental income may support the completed project?',help:'Treat unverified rent as an assumption and note whether the plan still works without it.',type:'textarea',concern:'complete',impact:'important'},
  {id:'stopConditions',section:'decision boundaries',text:'What findings would cause us to pause, reduce scope, or stop?',help:'Defining limits now helps distinguish a manageable challenge from an unacceptable risk.',type:'textarea',concern:'possible',impact:'critical'}
];
const packageSections = ['Project overview','Borrower profile','Income documentation','Assets and reserves','Debt and credit summary','Property and title information','Existing project investment','Site and permit information','Construction scope','Preliminary budget','Construction timeline','Temporary housing plan','Completed-project cash flow','Rental income strategy','Risk and contingency plan','Supporting documents','Lender questions and responses'];
const freshState = () => ({version:1,currentQuestion:0,intakeStarted:false,intakeComplete:false,answers:{},customItems:[],evidence:[],package:Object.fromEntries(packageSections.map(x=>[x,'not-started'])),lastSaved:null,lastBackup:null});
let state = load();
let selectedClass='assumption';
const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
function load(){try{return {...freshState(),...JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}}catch{return freshState()}}
function save(show=true){state.lastSaved=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(state));renderSave();if(show)toast('saved locally')}
function fmt(iso){return iso?new Date(iso).toLocaleString():'—'}
function renderSave(){$('#lastSaved').textContent=state.lastSaved?`Last saved ${fmt(state.lastSaved)}`:'No responses yet';$('#backupLocal').textContent=fmt(state.lastSaved);$('#backupDownload').textContent=state.lastBackup?fmt(state.lastBackup):'never';const protectedNow=!!state.lastBackup;$('#backupHealth').textContent=protectedNow?'downloaded backup available':'local only';$('#backupHealth').className=`health ${protectedNow?'protected':'local'}`;$('#backupMessage').textContent=protectedNow?'A downloadable backup has been created. Newer changes may still need another backup.':'Your responses are automatically saved in this browser on this device.'}
function showView(id){$$('.view').forEach(v=>v.classList.remove('active-view'));$(`#${id}`).classList.add('active-view');$$('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));$('#nav').classList.add('hidden');if(id==='concerns')renderConcerns();if(id==='register')renderRegister();if(id==='evidence')renderEvidence();if(id==='package')renderPackage();if(id==='backup')renderSave()}
function renderQuestion(){if(!state.intakeStarted){$('#intakeIntro').classList.remove('hidden');$('#questionCard').classList.add('hidden');return}$('#intakeIntro').classList.add('hidden');if(state.currentQuestion>=questions.length){state.intakeComplete=true;save(false);$('#questionCard').classList.add('hidden');$('#intakeComplete').classList.remove('hidden');return}$('#intakeComplete').classList.add('hidden');$('#questionCard').classList.remove('hidden');const q=questions[state.currentQuestion],a=state.answers[q.id]||{};$('#questionSection').textContent=q.section;$('#questionText').textContent=q.text;$('#questionHelp').textContent=q.help;$('#questionCount').textContent=`${state.currentQuestion+1} of ${questions.length}`;$('#answerArea').innerHTML=q.type==='textarea'?`<textarea id="answerInput" rows="6" placeholder="Enter what you know so far…"></textarea>`:`<input id="answerInput" type="text" placeholder="Enter what you know so far…" />`;$('#answerInput').value=a.value||'';selectedClass=a.state||'assumption';renderClass();$('#backBtn').disabled=state.currentQuestion===0}
function renderClass(){$$('.segmented button').forEach(b=>b.classList.toggle('active',b.dataset.state===selectedClass))}
function collectQuestion(forceUnknown=false){const q=questions[state.currentQuestion];const value=$('#answerInput').value.trim();state.answers[q.id]={value:forceUnknown?'':value,state:forceUnknown?'unknown':selectedClass,impact:q.impact,concern:q.concern,updated:new Date().toISOString()};if(q.evidence&&!state.evidence.some(e=>e.sourceQuestion===q.id)){state.evidence.push({id:crypto.randomUUID(),name:q.evidence,status:'requested',fileName:'',link:'',note:`Requested by: ${q.text}`,sourceQuestion:q.id})}}
function allItems(){const fromQ=questions.filter(q=>state.answers[q.id]).map(q=>({id:q.id,title:q.text,note:state.answers[q.id].value||'No answer yet',state:state.answers[q.id].state,impact:q.impact,concern:q.concern,source:'intake'}));return [...fromQ,...state.customItems]}
function renderConcerns(){const items=allItems();$('#concernGrid').innerHTML=concerns.map(c=>{const rel=items.filter(i=>i.concern===c.id),counts={known:0,assumption:0,unknown:0};rel.forEach(i=>counts[i.state]++);const score=rel.length?Math.round((counts.known+counts.assumption*.45)/rel.length*100):0;const critical=rel.find(i=>i.state==='unknown'&&i.impact==='critical');return `<article class="card concern-card"><p class="eyebrow">${score}% evidence-supported</p><h3>${c.title}</h3><div class="meter"><span style="width:${score}%"></span></div><div class="counts"><span class="pill known">${counts.known} known</span><span class="pill assumption">${counts.assumption} assumptions</span><span class="pill unknown">${counts.unknown} unknowns</span></div><p class="next-action"><strong>Next unresolved:</strong> ${critical?critical.title:(counts.unknown?'Resolve remaining unknowns':'Continue validating assumptions')}</p></article>`}).join('')}
function renderRegister(){const items=allItems(),counts={known:0,assumption:0,unknown:0};items.forEach(i=>counts[i.state]++);$('#registerSummary').innerHTML=['known','assumption','unknown'].map(k=>`<div class="summary-card"><small>${k}${k==='assumption'?'s':''}</small><strong>${counts[k]}</strong></div>`).join('')+`<div class="summary-card"><small>critical unknowns</small><strong>${items.filter(i=>i.state==='unknown'&&i.impact==='critical').length}</strong></div>`;$('#registerBody').innerHTML=items.length?items.map(i=>`<tr><td>${escapeHtml(i.title)}</td><td><span class="pill ${i.state}">${i.state}</span></td><td>${i.impact}</td><td>${concerns.find(c=>c.id===i.concern)?.title||'General'}</td><td>${escapeHtml(i.note||'')}</td><td><button class="ghost compact edit-item" data-id="${i.id}">edit</button></td></tr>`).join(''):`<tr><td colspan="6"><small>No items yet. Begin the guided intake or add one manually.</small></td></tr>`;$$('.edit-item').forEach(b=>b.onclick=()=>openItem(b.dataset.id))}
function openItem(id=''){const item=allItems().find(i=>i.id===id);$('#dialogTitle').textContent=item?'Edit item':'Add item';$('#itemId').value=id;$('#itemTitle').value=item?.title||'';$('#itemState').value=item?.state||'assumption';$('#itemImpact').value=item?.impact||'important';$('#itemConcern').innerHTML=concerns.map(c=>`<option value="${c.id}">${c.title}</option>`).join('');$('#itemConcern').value=item?.concern||'possible';$('#itemNote').value=item?.note||'';$('#itemDialog').showModal()}
function saveItem(){const id=$('#itemId').value,title=$('#itemTitle').value.trim();if(!title)return;const data={id:id||crypto.randomUUID(),title,state:$('#itemState').value,impact:$('#itemImpact').value,concern:$('#itemConcern').value,note:$('#itemNote').value.trim(),source:'custom'};if(id&&questions.some(q=>q.id===id)){const q=questions.find(q=>q.id===id);state.answers[id]={...(state.answers[id]||{}),value:data.note,state:data.state,impact:data.impact,concern:data.concern};q.text=data.title}else{const ix=state.customItems.findIndex(i=>i.id===id);if(ix>=0)state.customItems[ix]=data;else state.customItems.push(data)}save(false);renderRegister()}
function renderEvidence(){$('#evidenceList').innerHTML=state.evidence.length?state.evidence.map(e=>`<article class="card list-card"><div><h3>${escapeHtml(e.name)}</h3><p>${e.fileName?`Local file recorded: ${escapeHtml(e.fileName)}`:'No local file recorded'}${e.link?` · secure link added`:''}</p>${e.note?`<p><small>${escapeHtml(e.note)}</small></p>`:''}</div><div class="list-actions"><span class="pill ${e.status==='reviewed'?'known':e.status==='requested'?'unknown':'assumption'}">${e.status}</span>${e.link?`<a class="ghost compact" href="${escapeAttr(e.link)}" target="_blank" rel="noopener">open link</a>`:''}<button class="ghost compact delete-evidence" data-id="${e.id}">remove</button></div></article>`).join(''):`<div class="card"><p>No document requests or records yet.</p></div>`;$$('.delete-evidence').forEach(b=>b.onclick=()=>{state.evidence=state.evidence.filter(e=>e.id!==b.dataset.id);save(false);renderEvidence()})}
function renderPackage(){const vals=Object.values(state.package),weights={'not-started':0,'in-progress':.45,'ready':.8,'validated':1},pct=Math.round(vals.reduce((s,v)=>s+weights[v],0)/vals.length*100);$('#packagePercent').textContent=`${pct}%`;$('#packageList').innerHTML=packageSections.map(name=>`<article class="card package-row"><div><h3>${name}</h3><p>${packageHint(name)}</p></div><select data-package="${name}"><option value="not-started">Not started</option><option value="in-progress">In progress</option><option value="ready">Ready</option><option value="validated">Validated</option></select></article>`).join('');$$('[data-package]').forEach(s=>{s.value=state.package[s.dataset.package];s.onchange=()=>{state.package[s.dataset.package]=s.value;save(false);renderPackage()}})}
function packageHint(name){const map={'Project overview':'Narrative, objective, property, and funding request.','Borrower profile':'Employment, experience, and borrower background.','Income documentation':'Verified income records for all borrowers.','Assets and reserves':'Available cash, protected reserves, and other assets.','Debt and credit summary':'Current balances, payments, and credit position.','Property and title information':'Purchase terms, recorded documents, and title status.','Existing project investment':'Cash and completed work already invested.','Site and permit information':'Approvals, septic, survey, permits, and constraints.','Construction scope':'Required, deferred, and optional work.','Preliminary budget':'Costs, allowances, and contingency.','Construction timeline':'Milestones, duration, and schedule risks.','Temporary housing plan':'Living arrangement and fallback plan.','Completed-project cash flow':'Permanent payment and household affordability.','Rental income strategy':'Supported rents and no-rent stress case.','Risk and contingency plan':'Delay, overrun, reserve, and stop conditions.','Supporting documents':'Indexed evidence and secure links.','Lender questions and responses':'External feedback and validated requirements.'};return map[name]}
function exportBackup(){state.lastBackup=new Date().toISOString();save(false);const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`monticellOPS-mission2-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);renderSave();toast('backup downloaded')}
function importBackup(file){const r=new FileReader();r.onload=()=>{try{const data=JSON.parse(r.result);if(!data.version||!data.answers)throw new Error();state={...freshState(),...data,lastSaved:new Date().toISOString()};save(false);renderQuestion();renderSave();toast('backup restored')}catch{toast('that file is not a valid Mission 2 backup')}};r.readAsText(file)}
function escapeHtml(s=''){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function escapeAttr(s=''){return escapeHtml(s)}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2200)}
$('#menuBtn').onclick=()=>{$('#nav').classList.toggle('hidden');$('#menuBtn').setAttribute('aria-expanded',!$('#nav').classList.contains('hidden'))};$$('.nav button').forEach(b=>b.onclick=()=>showView(b.dataset.view));
$('#beginBtn').onclick=()=>{state.intakeStarted=true;save(false);renderQuestion()};
$$('.segmented button').forEach(b=>b.onclick=()=>{selectedClass=b.dataset.state;renderClass()});
$('#saveNextBtn').onclick=()=>{collectQuestion(false);state.currentQuestion++;save(false);renderQuestion()};
$('#skipBtn').onclick=()=>{collectQuestion(true);state.currentQuestion++;save(false);renderQuestion()};
$('#backBtn').onclick=()=>{if(state.currentQuestion>0){state.currentQuestion--;save(false);renderQuestion()}};
$('#reviewBtn').onclick=()=>showView('concerns');
$('#addItemBtn').onclick=()=>openItem();$('#itemSave').onclick=saveItem;
$('#addEvidenceBtn').onclick=()=>{$('#evidenceForm').reset();$('#evidenceDialog').showModal()};
$('#evidenceSave').onclick=()=>{const name=$('#evidenceName').value.trim();if(!name)return;const file=$('#evidenceFile').files[0];state.evidence.push({id:crypto.randomUUID(),name,status:$('#evidenceStatus').value,fileName:file?.name||'',fileType:file?.type||'',fileSize:file?.size||0,link:$('#evidenceLink').value.trim(),note:$('#evidenceNote').value.trim()});save(false);renderEvidence()};
$('#exportBtn').onclick=exportBackup;$('#importInput').onchange=e=>e.target.files[0]&&importBackup(e.target.files[0]);
$('#serverBtn').onclick=()=>toast('server backup is not connected yet');
$('#clearBtn').onclick=()=>{if(confirm('Clear all locally stored Mission 2 data from this browser?')){localStorage.removeItem(STORAGE_KEY);state=freshState();renderQuestion();renderSave();showView('intake');toast('local Mission 2 data cleared')}};
renderSave();renderQuestion();renderPackage();
