'use strict';
const STORAGE_KEY='monticellOPS_mission2_v3';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const uid=()=>globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`;
const concerns=[
{id:'qualification',title:'Can we qualify for financing?'},{id:'inProcess',title:'Can we afford the construction period?'},{id:'family',title:'Can the family handle the transition?'},{id:'temporary',title:'Could we get stuck living in the trailer?'},{id:'complete',title:'Can we afford the completed project?'},{id:'possible',title:'Is the overall plan actually possible?'}];
const questions=[
{id:'borrowers',section:'household position',text:'Who is expected to apply for the construction loan?',help:'List the intended borrowers and relevant employment context.',type:'textarea',concern:'qualification',impact:'critical'},
{id:'income',section:'household position',text:'What dependable gross income should a lender evaluate?',help:'Enter current annual or monthly income. Paystubs and W-2s can verify it later.',type:'textarea',concern:'qualification',impact:'critical',evidence:'Recent paystubs and two years of W-2s'},
{id:'debts',section:'household position',text:'What recurring debts and minimum monthly payments exist?',help:'Include credit cards, vehicles, student loans, personal loans, and other required payments.',type:'textarea',concern:'qualification',impact:'critical',evidence:'Current debt statements or credit report'},
{id:'credit',section:'household position',text:'What is currently known about borrower credit?',help:'Scores, recent balance reductions, late payments, disputes, or anything a lender may need explained.',type:'textarea',concern:'qualification',impact:'critical',evidence:'Current credit reports or lender credit pull'},
{id:'cash',section:'household position',text:'How much cash is available, and how much must remain protected?',help:'Separate project cash from the minimum family reserve that should not be consumed.',type:'textarea',concern:'inProcess',impact:'critical',evidence:'Recent bank or investment statements'},
{id:'landTerms',section:'property and transaction',text:'What are the land purchase terms and remaining amount due?',help:'Include purchase price, amount already paid, remaining balance, and timing requirements.',type:'textarea',concern:'possible',impact:'critical',evidence:'Purchase agreement, amendments, and payoff documentation'},
{id:'title',section:'property and transaction',text:'What is known about title, deed transfer, and existing encumbrances?',help:'Record what has been verified and what still needs title or attorney confirmation.',type:'textarea',concern:'possible',impact:'critical',evidence:'Title report, recorded short plat, and relevant legal documents'},
{id:'approvals',section:'property and transaction',text:'Which approvals and site documents are already complete?',help:'Short plat, survey, septic, zoning, permits, engineering, utility information, and other evidence.',type:'textarea',concern:'possible',impact:'important',evidence:'Recorded plat, survey, septic approval, permits, and site documents'},
{id:'requiredScope',section:'project scope',text:'What must be included in the funded project?',help:'Describe the minimum acceptable house, site work, utilities, temporary housing, and other required construction.',type:'textarea',concern:'possible',impact:'critical'},
{id:'deferredScope',section:'project scope',text:'What can be deferred or removed if financing requires a smaller first phase?',help:'Separate necessities from later phases, upgrades, and optional structures.',type:'textarea',concern:'possible',impact:'important'},
{id:'budget',section:'project scope',text:'What is the current best estimate of total project cost?',help:'Include land payoff, construction, site work, permits, soft costs, contingency, and financing costs.',type:'textarea',concern:'possible',impact:'critical',evidence:'Builder bids, estimates, quantity takeoffs, and preliminary budget'},
{id:'timeline',section:'construction period',text:'What construction duration should we plan around?',help:'Use a realistic range and identify major schedule dependencies.',type:'textarea',concern:'temporary',impact:'critical',evidence:'Builder or lender schedule guidance'},
{id:'currentHousing',section:'construction period',text:'Which current housing costs continue before move-in?',help:'Rent, trailer payment, storage, utilities, commuting, and any overlap with construction payments.',type:'textarea',concern:'inProcess',impact:'critical'},
{id:'drawPayment',section:'construction period',text:'What do we currently assume construction-loan payments will look like?',help:'Record interest-only assumptions, draw timing, fees, and anything awaiting lender confirmation.',type:'textarea',concern:'inProcess',impact:'critical',evidence:'Lender construction-loan terms or worksheet'},
{id:'reserve',section:'construction period',text:'What reserve would make the family feel adequately protected?',help:'Consider delays, cost overruns, income interruption, emergency expenses, and moving costs.',type:'textarea',concern:'inProcess',impact:'critical'},
{id:'familyNeeds',section:'family transition',text:'What would the kids and family need for the construction period to remain tolerable?',help:'Privacy, school routines, internet, pets, storage, space, commute, and personal boundaries all count.',type:'textarea',concern:'family',impact:'critical'},
{id:'trailerLimit',section:'temporary housing',text:'What is the maximum acceptable time living in the trailer?',help:'Define the family limit and what warning signs would trigger a change of plan.',type:'textarea',concern:'temporary',impact:'critical'},
{id:'fallback',section:'temporary housing',text:'What is the fallback if construction is delayed beyond that limit?',help:'Identify a rental, partial occupancy, temporary unit, family help, or another viable exit from trailer living.',type:'textarea',concern:'temporary',impact:'critical'},
{id:'completedPayment',section:'completed project',text:'What permanent monthly payment range appears sustainable?',help:'Include principal, interest, taxes, insurance, utilities, and expected maintenance.',type:'textarea',concern:'complete',impact:'critical'},
{id:'rentalIncome',section:'completed project',text:'What rental income may exist, and how conservative should we be?',help:'Separate lender-usable income from hoped-for income. Include a no-rent stress case.',type:'textarea',concern:'complete',impact:'important',evidence:'Market rent research, lease estimates, or appraiser/lender guidance'},
{id:'monthlyBuffer',section:'completed project',text:'What monthly buffer should remain after all completed-project costs?',help:'Define the surplus needed for normal family life, savings, repairs, and uncertainty.',type:'textarea',concern:'complete',impact:'critical'},
{id:'stopConditions',section:'decision boundaries',text:'What conditions would make us pause, reduce scope, or stop?',help:'Examples: insufficient reserves, payment above a limit, unacceptable trailer duration, low appraisal, or unsupported budget.',type:'textarea',concern:'possible',impact:'critical'},
{id:'lenderQuestions',section:'external validation',text:'What must a lender answer before this plan feels real?',help:'Capture qualification, loan structure, appraisal, reserves, builder rules, draw process, rental income, and timing questions.',type:'textarea',concern:'qualification',impact:'important'}];
const packageSections=['Project overview','Borrower profile','Income documentation','Assets and reserves','Debt and credit summary','Property and title information','Existing project investment','Site and permit information','Construction scope','Preliminary budget','Construction timeline','Temporary housing plan','Completed-project cash flow','Rental income strategy','Risk and contingency plan','Supporting documents','Lender questions and responses'];
const scenarioDefaults=[{id:'base',name:'Base plan',rate:7,totalLoan:750000,months:12,currentHousing:3000,constructionPayment:2500,postPayment:6000,rentalIncome:2000,otherMonthly:4500,reserve:25000},{id:'conservative',name:'Conservative plan',rate:8,totalLoan:800000,months:15,currentHousing:3000,constructionPayment:3200,postPayment:6800,rentalIncome:1200,otherMonthly:4700,reserve:35000},{id:'stress',name:'Stress case',rate:9,totalLoan:850000,months:18,currentHousing:3000,constructionPayment:4000,postPayment:7600,rentalIncome:0,otherMonthly:5000,reserve:50000}];
const planningBaselineAnswers={
borrowers:{value:'Christopher George Couevas and Nicole Joy Couevas are expected to apply together. Both are employed by Boeing. Christopher has worked at Boeing continuously since 2008 and currently earns approximately $160,000 per year. Nicole joined Boeing as a direct-hire union composite fabricator, grade 4, in January 2026 after more than 18 years as an educator and project manager.',state:'assumption',impact:'critical',concern:'qualification'},
income:{value:'Christopher: approximately $160,000 annual Boeing W-2 income. Nicole: current Boeing grade 4 income; exact annualized base pay, overtime history, and lender-usable income still need to be documented. The financing presentation should rely on dependable W-2 income and not require Unkillable Engineering revenue.',state:'assumption',impact:'critical',concern:'qualification'},
debts:{value:'Known recurring obligations include relatively high credit-card minimum payments, one vehicle loan with roughly one year remaining, a financed travel trailer about halfway through its term, and student loans in both borrowers’ names. $16,500 was recently paid toward revolving balances, bringing total reported utilization to approximately 47.9%, subject to statement reporting and lender verification.',state:'assumption',impact:'critical',concern:'qualification'},
credit:{value:'Credit-card utilization was recently reduced to approximately 47.9% after $16,500 in payments. Exact current scores, bureau reporting dates, account-level utilization, and lender underwriting treatment remain unknown until updated balances report and a lender reviews credit.',state:'assumption',impact:'critical',concern:'qualification'},
cash:{value:'Available cash and the amount that must remain protected need to be refreshed. A recent large credit-card paydown intentionally preserved only a small immediate cash cushion until the next paycheck, so this figure should not be treated as a stable project reserve.',state:'unknown',impact:'critical',concern:'inProcess'},
landTerms:{value:'Lot 2 is a 2.5-acre parcel created from an 11.4-acre parent parcel on Camano Island. Purchase price is $350,000. $100,000 has already been paid. The remaining $250,000 is due in connection with deed recording/transfer under the purchase agreement. The intended financing structure is a construction-to-permanent loan covering the land balance and construction.',state:'known',impact:'critical',concern:'possible'},
title:{value:'Christopher and Nicole intend to take title as community property with right of survivorship. The short plat is recorded as AFN 4598873. The seller retains an encumbrance/note involving the parent parcel, so current title, payoff, deed-transfer mechanics, and closing requirements still require formal title and lender confirmation.',state:'assumption',impact:'critical',concern:'possible'},
approvals:{value:'The short plat received final approval and was recorded in April 2026. The parcel is Rural Residential and has septic approval supporting six bedrooms. Existing work includes subdivision, permitting, survey, and related site-development effort funded and managed by the buyers. The exact lender-ready document index still needs to be assembled and checked.',state:'assumption',impact:'important',concern:'possible'},
requiredScope:{value:'Current target scope: pay the remaining land balance; build the primary residence with a finished daylight/walkout basement ADU; provide temporary family housing during construction; complete necessary site work, utilities, and access; and ideally include a detached 40×60 shop. The primary residence is currently envisioned as 3 bedrooms, with a 2-bedroom basement ADU. Some lower-level area may become an attached 2-car garage depending on final design and weather considerations.',state:'assumption',impact:'critical',concern:'possible'},
deferredScope:{value:'Potentially deferrable items include portions of the detached 40×60 shop, trailer cover, nonessential finish upgrades, landscaping, some property-optimization work, and a separate detached 1-bedroom unit. The exact minimum viable funded phase has not yet been locked.',state:'assumption',impact:'important',concern:'possible'},
budget:{value:'A lender-ready total project budget has not yet been validated. It must include the $250,000 land payoff, house construction, basement ADU, site work, utilities, permits and professional fees, financing costs, contingency, temporary-housing costs, and any shop scope included in the first phase.',state:'unknown',impact:'critical',concern:'possible'},
timeline:{value:'Construction duration has not been validated by a builder or lender. Planning should include permitting/design completion, lender closing, site work, vertical construction, inspections, utility completion, and a realistic delay allowance.',state:'unknown',impact:'critical',concern:'temporary'},
currentHousing:{value:'Current rent is approximately $3,000 per month. Additional construction-period costs may include the travel-trailer payment, utilities, storage, commuting, site costs, and overlap between rent and construction-loan payments. Exact monthly overlap needs to be modeled.',state:'assumption',impact:'critical',concern:'inProcess'},
drawPayment:{value:'The intended loan is construction-to-permanent, but interest-only draw payment behavior, fees, required reserves, land-equity treatment, and timing have not yet been confirmed by an active lender.',state:'unknown',impact:'critical',concern:'inProcess'},
reserve:{value:'The protected family reserve has not been set. It should be determined from actual household spending, expected construction-period carrying costs, delay exposure, and the family’s comfort threshold—not from a generic rule alone.',state:'unknown',impact:'critical',concern:'inProcess'},
familyNeeds:{value:'The plan must preserve school and work routines, reliable internet, privacy, sleeping space, storage, weather protection, and a tolerable commute. Niki’s concern is not merely whether temporary housing is technically possible, but whether the family can live through the construction period without an open-ended or destabilizing experience.',state:'assumption',impact:'critical',concern:'family'},
trailerLimit:{value:'No firm maximum trailer-living duration has been agreed. This should be established as a family decision and tied to schedule checkpoints and a fallback trigger.',state:'unknown',impact:'critical',concern:'temporary'},
fallback:{value:'A reliable fallback for construction delay has not been selected. Options to evaluate include maintaining rent longer, a temporary rental, phased/partial occupancy when legally possible, or another temporary-housing arrangement that prevents trailer living from becoming indefinite.',state:'unknown',impact:'critical',concern:'temporary'},
completedPayment:{value:'A sustainable completed-project payment range has not yet been established from verified income, debts, taxes, insurance, utilities, maintenance, and conservative rental treatment.',state:'unknown',impact:'critical',concern:'complete'},
rentalIncome:{value:'The current property concept may support a 2-bedroom basement ADU and, later, a detached 1-bedroom unit. The working belief is that one long-term rental and one short-term rental may be allowed, but zoning, operating rules, market rent, appraisal treatment, and lender-usable rental income must all be verified. Feasibility should include a no-rent stress case.',state:'assumption',impact:'important',concern:'complete'},
monthlyBuffer:{value:'The required monthly surplus after all completed-project costs has not been defined. It should protect normal family life, savings, maintenance, repairs, and uncertainty rather than merely producing a technically positive number.',state:'unknown',impact:'critical',concern:'complete'},
stopConditions:{value:'Likely pause or scope-reduction triggers include an unsupported construction budget, inadequate protected reserves, a permanent payment above the family’s comfort limit, unacceptable temporary-housing duration, insufficient appraisal, title/closing obstacles, or lender terms that rely too heavily on uncertain rental or business income. Exact thresholds remain to be agreed.',state:'assumption',impact:'critical',concern:'possible'},
lenderQuestions:{value:'Confirm: borrower qualification and usable income; treatment of recently reduced revolving balances; land equity and the remaining seller payoff; title and deed-transfer mechanics; construction-to-permanent structure; builder eligibility; appraisal method; contingency and reserve requirements; draw process and interest payments; inclusion or deferral of the shop; treatment of ADU/rental income; temporary-housing costs; and realistic closing timeline.',state:'assumption',impact:'important',concern:'qualification'}
};
const baselineEvidence=[
{id:'baseline-plat',name:'Recorded short plat — AFN 4598873',status:'available',fileName:'',fileType:'',fileSize:0,fileDate:'',link:'',note:'Known to exist; attach or link the recorded document.'},
{id:'baseline-agreement',name:'Purchase agreement and amendments',status:'available',fileName:'',fileType:'',fileSize:0,fileDate:'',link:'',note:'Attorney-reviewed agreement; attach the current executed version and any extension.'},
{id:'baseline-septic',name:'Six-bedroom septic approval',status:'available',fileName:'',fileType:'',fileSize:0,fileDate:'',link:'',note:'Known project approval; attach current approval and site plan.'},
{id:'baseline-income',name:'Current Boeing paystubs and two years of W-2s',status:'requested',fileName:'',fileType:'',fileSize:0,fileDate:'',link:'',note:'Needed to convert income assumptions into verified lender evidence.'},
{id:'baseline-credit',name:'Updated debt statements / lender credit report',status:'requested',fileName:'',fileType:'',fileSize:0,fileDate:'',link:'',note:'Needed after recent $16,500 revolving-debt paydown reports.'},
{id:'baseline-budget',name:'Builder estimate and lender-ready project budget',status:'requested',fileName:'',fileType:'',fileSize:0,fileDate:'',link:'',note:'Critical missing evidence for feasibility.'},
{id:'baseline-title',name:'Current title report and seller payoff requirements',status:'requested',fileName:'',fileType:'',fileSize:0,fileDate:'',link:'',note:'Needed to validate closing structure and encumbrances.'}
];
const baselinePackage={
'Project overview':'ready','Borrower profile':'in-progress','Income documentation':'in-progress','Assets and reserves':'not-started','Debt and credit summary':'in-progress','Property and title information':'in-progress','Existing project investment':'ready','Site and permit information':'in-progress','Construction scope':'in-progress','Preliminary budget':'not-started','Construction timeline':'not-started','Temporary housing plan':'in-progress','Completed-project cash flow':'not-started','Rental income strategy':'in-progress','Risk and contingency plan':'in-progress','Supporting documents':'in-progress','Lender questions and responses':'in-progress'
};
function freshState({blank=false}={}){return{version:3,baselineVersion:blank?null:'planning-2026-07-19',currentQuestion:0,intakeStarted:false,answers:blank?{}:structuredClone(planningBaselineAnswers),customItems:[],evidence:blank?[]:structuredClone(baselineEvidence),validations:[],scenarios:structuredClone(scenarioDefaults),package:blank?Object.fromEntries(packageSections.map(x=>[x,'not-started'])):{...baselinePackage},lastSaved:null,lastBackup:null}}
let state=load(),selectedClass='known';
function load(){try{const parsed=JSON.parse(localStorage.getItem(STORAGE_KEY));return parsed?{...freshState(),...parsed}:freshState()}catch{return freshState()}}
function save(show=true){state.lastSaved=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(state));renderSave();if(show)toast('saved locally')}
function showView(id){$$('.view').forEach(v=>v.classList.toggle('active-view',v.id===id));$$('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));if(innerWidth<760)$('#nav').classList.add('hidden');({concerns:renderConcerns,register:renderRegister,evidence:renderEvidence,scenarios:renderScenarios,validation:renderValidation,package:renderPackage,backup:renderSave}[id]||(()=>{}))();scrollTo({top:0,behavior:'smooth'})}
function renderSave(){const dt=state.lastSaved?new Date(state.lastSaved):null;$('#lastSaved').textContent=dt?`Last save ${dt.toLocaleString()}`:'No responses yet';$('#backupLocal').textContent=dt?dt.toLocaleString():'—';$('#backupDownload').textContent=state.lastBackup?new Date(state.lastBackup).toLocaleString():'never';const protectedNow=state.lastBackup&&state.lastSaved&&new Date(state.lastBackup)>=new Date(state.lastSaved);$('#backupHealth').textContent=protectedNow?'backup current':'local only';$('#backupHealth').className=`health ${protectedNow?'protected':'local'}`;$('#backupMessage').textContent=protectedNow?'Your latest saved progress has been downloaded as a backup.':'Your responses are saved locally. Download a backup to protect against browser or device loss.'}
function renderQuestion(){const intro=$('#intakeIntro'),card=$('#questionCard'),done=$('#intakeComplete');intro.classList.toggle('hidden',state.intakeStarted);if(!state.intakeStarted){card.classList.add('hidden');done.classList.add('hidden');return}if(state.currentQuestion>=questions.length){card.classList.add('hidden');done.classList.remove('hidden');return}done.classList.add('hidden');card.classList.remove('hidden');const q=questions[state.currentQuestion],a=state.answers[q.id]||{};$('#questionSection').textContent=q.section;$('#questionText').textContent=q.text;$('#questionHelp').textContent=q.help;$('#questionCount').textContent=`${state.currentQuestion+1} of ${questions.length}`;$('#questionProgress').innerHTML=questions.map((item,i)=>`<span class="${state.answers[item.id]?'done':i===state.currentQuestion?'current':''}"></span>`).join('');$('#answerArea').innerHTML=`<label>Your current answer<textarea id="answerInput" placeholder="Enter what is known now. You can revise this later."></textarea></label>`;$('#answerInput').value=a.value||'';selectedClass=a.state||'known';renderClass();$('#backBtn').disabled=state.currentQuestion===0}
function renderClass(){$$('.segmented button').forEach(b=>b.classList.toggle('active',b.dataset.state===selectedClass))}
function collectQuestion(forceUnknown=false){const q=questions[state.currentQuestion],value=$('#answerInput').value.trim();state.answers[q.id]={value:forceUnknown?'':value,state:forceUnknown?'unknown':selectedClass,impact:q.impact,concern:q.concern,updated:new Date().toISOString()};if(q.evidence&&!state.evidence.some(e=>e.sourceQuestion===q.id))state.evidence.push({id:uid(),name:q.evidence,status:'requested',fileName:'',fileType:'',fileSize:0,fileDate:'',link:'',note:`Requested by intake: ${q.text}`,sourceQuestion:q.id})}
function allItems(){const intake=questions.filter(q=>state.answers[q.id]).map(q=>({id:q.id,title:q.text,note:state.answers[q.id].value||'No answer yet',state:state.answers[q.id].state,impact:state.answers[q.id].impact||q.impact,concern:state.answers[q.id].concern||q.concern,source:'intake'}));return[...intake,...state.customItems]}
function renderConcerns(){const items=allItems();$('#concernGrid').innerHTML=concerns.map(c=>{const rel=items.filter(i=>i.concern===c.id),counts={known:0,assumption:0,unknown:0};rel.forEach(i=>counts[i.state]++);const score=rel.length?Math.round((counts.known+counts.assumption*.4)/rel.length*100):0;const critical=rel.find(i=>i.state==='unknown'&&i.impact==='critical');const assumption=rel.find(i=>i.state==='assumption'&&i.impact==='critical');return`<article class="card concern-card"><p class="eyebrow">${score}% evidence-supported</p><h3>${c.title}</h3><div class="meter"><span style="width:${score}%"></span></div><div class="counts"><span class="pill known">${counts.known} known</span><span class="pill assumption">${counts.assumption} assumptions</span><span class="pill unknown">${counts.unknown} unknowns</span></div><p class="next-action"><strong>Next priority:</strong> ${escapeHtml(critical?.title||assumption?.title||(rel.length?'Continue strengthening evidence':'Begin guided intake'))}</p></article>`}).join('')}
function renderRegister(){const items=allItems(),counts={known:0,assumption:0,unknown:0};items.forEach(i=>counts[i.state]++);$('#registerSummary').innerHTML=['known','assumption','unknown'].map(k=>`<div class="summary-card"><small>${k}${k==='assumption'?'s':''}</small><strong>${counts[k]}</strong></div>`).join('')+`<div class="summary-card"><small>critical unknowns</small><strong>${items.filter(i=>i.state==='unknown'&&i.impact==='critical').length}</strong></div>`;$('#registerBody').innerHTML=items.length?items.map(i=>`<tr><td>${escapeHtml(i.title)}</td><td><span class="pill ${i.state}">${i.state}</span></td><td>${escapeHtml(i.impact)}</td><td>${escapeHtml(concerns.find(c=>c.id===i.concern)?.title||'General')}</td><td>${escapeHtml(i.note||'')}</td><td><button class="ghost compact edit-item" data-id="${i.id}">edit</button></td></tr>`).join(''):'<tr><td colspan="6" class="empty">No items yet. Begin guided intake or add one manually.</td></tr>';$$('.edit-item').forEach(b=>b.onclick=()=>openItem(b.dataset.id))}
function openItem(id=''){const item=allItems().find(i=>i.id===id);$('#dialogTitle').textContent=item?'Edit item':'Add item';$('#itemId').value=id;$('#itemTitle').value=item?.title||'';$('#itemState').value=item?.state||'assumption';$('#itemImpact').value=item?.impact||'important';$('#itemConcern').innerHTML=concerns.map(c=>`<option value="${c.id}">${c.title}</option>`).join('');$('#itemConcern').value=item?.concern||'possible';$('#itemNote').value=item?.note||'';$('#itemDialog').showModal()}
function saveItem(e){e.preventDefault();const id=$('#itemId').value,title=$('#itemTitle').value.trim();if(!title)return;const data={id:id||uid(),title,state:$('#itemState').value,impact:$('#itemImpact').value,concern:$('#itemConcern').value,note:$('#itemNote').value.trim(),source:'custom'};if(id&&questions.some(q=>q.id===id)){const q=questions.find(q=>q.id===id);state.answers[id]={...(state.answers[id]||{}),value:data.note,state:data.state,impact:data.impact,concern:data.concern,updated:new Date().toISOString()};q.text=data.title}else{const ix=state.customItems.findIndex(i=>i.id===id);if(ix>=0)state.customItems[ix]=data;else state.customItems.push(data)}save(false);$('#itemDialog').close();renderRegister()}
function renderEvidence(){$('#evidenceList').innerHTML=state.evidence.length?state.evidence.map(e=>`<article class="card list-card"><div><h3>${escapeHtml(e.name)}</h3><p>${e.fileName?`Local file recorded: ${escapeHtml(e.fileName)}`:'No local file recorded'}${e.fileDate?` · ${escapeHtml(e.fileDate)}`:''}${e.link?' · secure link added':''}</p>${e.note?`<p><small>${escapeHtml(e.note)}</small></p>`:''}</div><div class="list-actions"><span class="pill ${e.status==='reviewed'?'known':e.status==='requested'?'unknown':'assumption'}">${escapeHtml(e.status)}</span>${e.link?`<a class="ghost compact" href="${escapeAttr(e.link)}" target="_blank" rel="noopener">open link</a>`:''}<button class="ghost compact delete-evidence" data-id="${e.id}">remove</button></div></article>`).join(''):'<div class="card empty">No document requests or records yet.</div>';$$('.delete-evidence').forEach(b=>b.onclick=()=>{state.evidence=state.evidence.filter(e=>e.id!==b.dataset.id);save(false);renderEvidence()})}
function renderScenarios(){$('#scenarioGrid').innerHTML=state.scenarios.map(s=>{const buildCarry=(+s.currentHousing||0)+(+s.constructionPayment||0)+(+s.otherMonthly||0);const completed=(+s.postPayment||0)+(+s.otherMonthly||0)-(+s.rentalIncome||0);return`<article class="card scenario-card" data-scenario="${s.id}"><h3>${escapeHtml(s.name)}</h3><label>Total loan assumption<input type="number" data-field="totalLoan" value="${s.totalLoan}"></label><label>Interest rate assumption (%)<input type="number" step=".125" data-field="rate" value="${s.rate}"></label><label>Construction duration (months)<input type="number" data-field="months" value="${s.months}"></label><label>Current housing / month<input type="number" data-field="currentHousing" value="${s.currentHousing}"></label><label>Construction loan payment / month<input type="number" data-field="constructionPayment" value="${s.constructionPayment}"></label><label>Other household spending / month<input type="number" data-field="otherMonthly" value="${s.otherMonthly}"></label><label>Completed project payment / month<input type="number" data-field="postPayment" value="${s.postPayment}"></label><label>Rental income / month<input type="number" data-field="rentalIncome" value="${s.rentalIncome}"></label><label>Protected reserve<input type="number" data-field="reserve" value="${s.reserve}"></label><p class="small-note">Construction-period monthly outflow assumption</p><div class="scenario-output">${money(buildCarry)}</div><p class="small-note">Completed monthly outflow after rental income</p><div class="scenario-output">${money(completed)}</div></article>`}).join('');$$('[data-scenario] input').forEach(input=>input.onchange=()=>{const card=input.closest('[data-scenario]'),s=state.scenarios.find(x=>x.id===card.dataset.scenario);s[input.dataset.field]=Number(input.value)||0;save(false);renderScenarios()})}
function renderValidation(){$('#validationList').innerHTML=state.validations.length?state.validations.slice().reverse().map(v=>`<article class="card validation-entry"><div class="list-card"><div><p class="eyebrow">${escapeHtml(v.type)}</p><h3>${escapeHtml(v.source)}</h3><time>${escapeHtml(v.date||'Date not recorded')}</time></div><button class="ghost compact delete-validation" data-id="${v.id}">remove</button></div><p><strong>What we learned:</strong> ${escapeHtml(v.learned)}</p>${v.next?`<p><strong>Requirement / next action:</strong> ${escapeHtml(v.next)}</p>`:''}</article>`).join(''):'<div class="card empty">No lender, broker, builder, or advisor feedback has been recorded yet.</div>';$$('.delete-validation').forEach(b=>b.onclick=()=>{state.validations=state.validations.filter(v=>v.id!==b.dataset.id);save(false);renderValidation()})}
function renderPackage(){const vals=Object.values(state.package),weights={'not-started':0,'in-progress':.45,'ready':.8,'validated':1},pct=Math.round(vals.reduce((s,v)=>s+weights[v],0)/vals.length*100);$('#packagePercent').textContent=`${pct}%`;$('#packageList').innerHTML=packageSections.map(name=>`<article class="card package-row"><div><h3>${name}</h3><p>${packageHint(name)}</p></div><select data-package="${name}"><option value="not-started">Not started</option><option value="in-progress">In progress</option><option value="ready">Ready</option><option value="validated">Validated</option></select></article>`).join('');$$('[data-package]').forEach(s=>{s.value=state.package[s.dataset.package]||'not-started';s.onchange=()=>{state.package[s.dataset.package]=s.value;save(false);renderPackage()}})}
function packageHint(name){return({'Project overview':'Narrative, objective, property, and funding request.','Borrower profile':'Employment, experience, and borrower background.','Income documentation':'Verified income records for all borrowers.','Assets and reserves':'Available cash, protected reserves, and other assets.','Debt and credit summary':'Current balances, payments, and credit position.','Property and title information':'Purchase terms, recorded documents, and title status.','Existing project investment':'Cash and completed work already invested.','Site and permit information':'Approvals, septic, survey, permits, and constraints.','Construction scope':'Required, deferred, and optional work.','Preliminary budget':'Costs, allowances, and contingency.','Construction timeline':'Milestones, duration, and schedule risks.','Temporary housing plan':'Living arrangement and fallback plan.','Completed-project cash flow':'Permanent payment and household affordability.','Rental income strategy':'Supported rents and no-rent stress case.','Risk and contingency plan':'Delay, overrun, reserve, and stop conditions.','Supporting documents':'Indexed evidence and secure links.','Lender questions and responses':'External feedback and validated requirements.'})[name]}
function exportBackup(){state.lastBackup=new Date().toISOString();save(false);const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`monticellOPS-mission2-backup-${new Date().toISOString().slice(0,10)}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000);renderSave();toast('backup downloaded')}
function importBackup(file){const r=new FileReader();r.onload=()=>{try{const data=JSON.parse(r.result);if(!data.version||!data.answers)throw Error();state={...freshState(),...data,lastSaved:new Date().toISOString()};save(false);renderQuestion();renderSave();showView('intake');toast('backup restored')}catch{toast('not a valid Mission 2 backup')}};r.readAsText(file)}
function money(v){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(v||0)}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}const escapeAttr=escapeHtml;
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2200)}
$('#menuBtn').onclick=()=>{$('#nav').classList.toggle('hidden');$('#menuBtn').setAttribute('aria-expanded',String(!$('#nav').classList.contains('hidden')))};$$('.nav button').forEach(b=>b.onclick=()=>showView(b.dataset.view));
$('#beginBtn').onclick=()=>{state.intakeStarted=true;save(false);renderQuestion()};$$('.segmented button').forEach(b=>b.onclick=()=>{selectedClass=b.dataset.state;renderClass()});
$('#saveNextBtn').onclick=()=>{collectQuestion(false);state.currentQuestion++;save(false);renderQuestion()};$('#skipBtn').onclick=()=>{collectQuestion(true);state.currentQuestion++;save(false);renderQuestion()};$('#backBtn').onclick=()=>{if(state.currentQuestion>0){state.currentQuestion--;save(false);renderQuestion()}};$('#restartReviewBtn').onclick=()=>{state.currentQuestion=0;save(false);renderQuestion()};$('#reviewBtn').onclick=()=>showView('concerns');
$('#addItemBtn').onclick=()=>openItem();$('#itemForm').onsubmit=saveItem;
$('#addEvidenceBtn').onclick=()=>{$('#evidenceForm').reset();$('#evidenceDialog').showModal()};$('#evidenceForm').onsubmit=e=>{e.preventDefault();const name=$('#evidenceName').value.trim();if(!name)return;const file=$('#evidenceFile').files[0];state.evidence.push({id:uid(),name,status:$('#evidenceStatus').value,fileName:file?.name||'',fileType:file?.type||'',fileSize:file?.size||0,fileDate:file?.lastModified?new Date(file.lastModified).toLocaleDateString():'',link:$('#evidenceLink').value.trim(),note:$('#evidenceNote').value.trim()});save(false);$('#evidenceDialog').close();renderEvidence()};
$('#addValidationBtn').onclick=()=>{$('#validationForm').reset();$('#validationDate').value=new Date().toISOString().slice(0,10);$('#validationDialog').showModal()};$('#validationForm').onsubmit=e=>{e.preventDefault();state.validations.push({id:uid(),source:$('#validationSource').value.trim(),date:$('#validationDate').value,type:$('#validationType').value,learned:$('#validationLearned').value.trim(),next:$('#validationNext').value.trim()});save(false);$('#validationDialog').close();renderValidation()};
$('#exportBtn').onclick=exportBackup;$('#importInput').onchange=e=>e.target.files[0]&&importBackup(e.target.files[0]);$('#serverBtn').onclick=()=>toast('server backup is not connected yet');$('#clearBtn').onclick=()=>{if(confirm('Reset Mission 2 to the original planning baseline? This removes your edits on this device.')){localStorage.removeItem(STORAGE_KEY);state=freshState();save(false);renderQuestion();renderSave();showView('intake');toast('planning baseline restored')}};$('#blankBtn').onclick=()=>{if(confirm('Start with a completely blank Mission 2 for testing? This removes the planning baseline and all current edits on this device.')){localStorage.removeItem(STORAGE_KEY);state=freshState({blank:true});save(false);renderQuestion();renderSave();showView('intake');toast('blank test mission started')}};
renderSave();renderQuestion();renderPackage();
